= My ideal working environment

+++ Smart people who feel the need of continuous improvement and are not afraid of new technologies/methodologies

+++ Team not just a collection of individuals

+-+ 9-5 programmer/daycoders/Daytime Developers in a team

+++ People following "Clean code"/"Clean coder" principles, Agile/XP/DevOps practices, etc. Not just "willing to have in the future" or "have heard of".

+++ Automation, automation, automation (continuous  integration, continuous  deployment, automated release management, automated testing)

+++ Linux desktop environment

+++ Trading/Investment banking business

+++ Power napping room

== Technology
+++ Java 7/8

+++ Clojure (no commercial experiance required)

+++ KDB/q (no commercial experiance required)

+++ Git (GitHub, Stash)

+++ Gradle/Maven/Leiningen

+++ Jenkins/TeamCity/Bamboo, etc.

+-+ Java 5/6

+-+ JEE

+-+ .NET, C#

+-+ GUI (Swing)

+-+ Web UI (JSP, JSF, JavaScript, HTML)

+-+ Ant

+-+ make

+-+ VersionOne

== Test
Inspired by The Joel Test (http://wearebase.com/the-joel-test-and-our-engineering-process/) and The Programmer's Bill of Rights (http://blog.codinghorror.com/the-programmers-bill-of-rights/).

* Do you use distributed version control system? Which one?

* Do you use build automation tool? Which one?

* Can you make a deployment into your DEV, UAT, QA environment in one step?

* Do you make builds after each commit?

* Do you use issue tracking software? Which one?

* Are your version control, issue tracking, work tracking, deployment tools integrated?

* Is planning done on a regular basis?

* Are requirements and design decisions managed and properly understood by the whole team?

* Do programmers have productive working conditions?

** Do programmers have a monitor setting best suited for his or her task? What's the setting?
** Do programmers have a fast PC?
** Do programmers have their choice of mouse and keyboard?
** Do programmers a comfortable chair?
** Do programmers have a fast internet connection?
** Do programmers have quiet working conditions?
** Do programmers use a software / operating system of their choice?
** Do programmers have an access to power napping / rest room?

* Do you have fully automated tests?

** Unit?
** Integration?
** Performance?
** Regression?
** Acceptance?
** "Chaos Monkey"?

* Do new candidates write code as a part of interview process? During or before?

* Do new candidates review code during their interview?

* Is the customer represented within your process to provide regular feedback on your product?
